In [18]:
import pandas as pd

In [23]:
SICOR_COP_BASICO = pd.read_csv('BD\SICOR\SICOR_COP_BASICO.gz', sep=';', encoding='latin1', decimal=',')

In [24]:
SICOR_COP_BASICO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 991975 entries, 0 to 991974
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   #REF_BACEN          991975 non-null  int64
 1   NU_ORDEM            991975 non-null  int64
 2   DT_COMUNICACAO      991975 non-null  object
 3   DT_FIM_COLHEITA     991975 non-null  object
 4   DT_FIM_PLANTIO      991975 non-null  object
 5   DT_INICIO_COLHEITA  991975 non-null  object
 6   DT_INICIO_PLANTIO   991975 non-null  object
 7   CD_STATUS           991975 non-null  int64
 8   CD_CICLO_CULTIVAR   991975 non-null  int64
 9   CD_TIPO_SOLO        991975 non-null  int64
 10  CD_EVENTO           991975 non-null  int64
dtypes: int64(6), object(5)
memory usage: 83.2+ MB

In [25]:
SICOR_COP_BASICO.head()

,#REF_BACEN,NU_ORDEM,DT_COMUNICACAO,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INICIO_COLHEITA,DT_INICIO_PLANTIO,CD_STATUS,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,CD_EVENTO
0,3177940,1,14/10/2014,15/11/2014,20/06/2014,01/11/2014,01/06/2014,2,3,3,17
1,3984587,2,12/12/2014,01/01/2015,03/09/2014,01/01/2015,03/09/2014,2,3,3,48
2,505043929,1,24/01/2018,20/05/2018,04/10/2017,15/02/2018,04/10/2017,2,1,3,17
3,513309520,1,30/05/2022,15/06/2022,07/02/2022,10/06/2022,03/02/2022,2,99,9,17
4,3402920,1,05/11/2014,07/12/2014,20/07/2014,30/07/2014,08/07/2014,2,3,3,17

In [27]:
SICOR_COP_BASICO.shape

(991975, 11)

In [28]:
SICOR_COP_BASICO.columns

Index(['#REF_BACEN', 'NU_ORDEM', 'DT_COMUNICACAO', 'DT_FIM_COLHEITA',
       'DT_FIM_PLANTIO', 'DT_INICIO_COLHEITA', 'DT_INICIO_PLANTIO',
       'CD_STATUS', 'CD_CICLO_CULTIVAR', 'CD_TIPO_SOLO', 'CD_EVENTO'],
      dtype='object')

In [29]:
list(SICOR_COP_BASICO.columns)

['#REF_BACEN',
 'NU_ORDEM',
 'DT_COMUNICACAO',
 'DT_FIM_COLHEITA',
 'DT_FIM_PLANTIO',
 'DT_INICIO_COLHEITA',
 'DT_INICIO_PLANTIO',
 'CD_STATUS',
 'CD_CICLO_CULTIVAR',
 'CD_TIPO_SOLO',
 'CD_EVENTO']

In [32]:
COP_BASICO = SICOR_COP_BASICO.rename( columns={'DT_COMUNICACAO': 'DATA_COMUNICACAO'})

In [34]:
COP_BASICO

,#REF_BACEN,NU_ORDEM,DATA_COMUNICACAO,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INICIO_COLHEITA,DT_INICIO_PLANTIO,CD_STATUS,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,CD_EVENTO
0,3177940,1,14/10/2014,15/11/2014,20/06/2014,01/11/2014,01/06/2014,2,3,3,17
1,3984587,2,12/12/2014,01/01/2015,03/09/2014,01/01/2015,03/09/2014,2,3,3,48
2,505043929,1,24/01/2018,20/05/2018,04/10/2017,15/02/2018,04/10/2017,2,1,3,17
3,513309520,1,30/05/2022,15/06/2022,07/02/2022,10/06/2022,03/02/2022,2,99,9,17
4,3402920,1,05/11/2014,07/12/2014,20/07/2014,30/07/2014,08/07/2014,2,3,3,17
...,...,...,...,...,...,...,...,...,...,...,...
991970,1319699,1,12/05/2014,25/05/2014,21/12/2013,16/05/2014,21/12/2013,2,3,9,48
991971,516580594,1,26/10/2023,15/12/2023,23/09/2023,01/12/2023,23/09/2023,2,99,3,17
991972,509995915,1,07/10/2020,05/11/2020,26/06/2020,20/10/2020,24/06/2020,2,2,2,48
991973,5611099,1,23/10/2015,07/12/2015,08/06/2015,30/07/2015,08/06/2015,2,1,3,24
991974,512483995,1,24/02/2022,20/04/2022,22/10/2021,15/03/2022,22/10/2021,2,1,9,48

In [35]:
COP_BASICO.iloc[1]

#REF_BACEN               3984587
NU_ORDEM                       2
DATA_COMUNICACAO      12/12/2014
DT_FIM_COLHEITA       01/01/2015
DT_FIM_PLANTIO        03/09/2014
DT_INICIO_COLHEITA    01/01/2015
DT_INICIO_PLANTIO     03/09/2014
CD_STATUS                      2
CD_CICLO_CULTIVAR              3
CD_TIPO_SOLO                   3
CD_EVENTO                     48
Name: 1, dtype: object